In [1]:
import numpy as np
#np.random.seed(12345)
#import matplotlib.pyplot as plt
#plt.rc("figure", figsize=(10, 6))
#np.set_printoptions(precision=4, suppress=True)


In [2]:
l = [1,2,3,4]

In [27]:
l_array = np.array([1,2,3,4])

In [4]:
print(l)
print(l_array)

[1, 2, 3, 4]
[1 2 3 4]


In [5]:
print(type(l))
print(type(l_array))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:


my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [10]:


my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))
type(my_arr)

numpy.ndarray

In [23]:
print(my_arr[0:10])

[0 1 2 3 4 5 6 7 8 9]


In [26]:


my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))
my_list[0:5]

[0, 1, 2, 3, 4]

In [25]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

871 µs ± 38.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
23.4 ms ± 577 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [37]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print(data)  
data.shape
type(data.dtype)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


numpy.dtype[float64]

In [42]:
x10 = data*10
print(x10)
print("\n")
print(x10 + 2)



[[ 15.  -1.  30.]
 [  0. -30.  65.]]


[[ 17.   1.  32.]
 [  2. -28.  67.]]


In [43]:
data.shape
#print(data.shape)


(2, 3)

In [47]:
data1 = [6, 7.5, 8, 0, 1]
print("This is the type of data1", type(data1))
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

This is the type of data1 <class 'list'>
[6.  7.5 8.  0.  1. ]
<class 'numpy.ndarray'>


In [48]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
arr2.ndim
arr2.shape
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [51]:
data_3d = [[1, 2, 3, 4], [5, 6, 7, 8], [11, 12, 13, 14]]
arr3 = np.array(data_3d)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14]])

In [52]:
arr3.ndim

2

In [53]:
arr3.shape

(3, 4)

In [54]:
arr1.ndim
arr1.shape
print(arr1.ndim)
print(arr1.shape)

1
(5,)


In [55]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [56]:
#np.zeros(10)

#np.zeros((3, 6))
np.empty((2, 3))

array([[ 17.,   1.,  32.],
       [  2., -28.,  67.]])

In [57]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
#arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1 = np.array([1, 2, 3])
#arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1)
#print(arr2.dtype)

[1 2 3]


In [64]:
arr = np.array([1, 2, 3, 4, 5])
print("This is dtype before conversion", arr.dtype)
float_arr = arr.astype(np.float64)

print("This is dtype AFTER conversion", float_arr.dtype)
float_arr

This is dtype before conversion int64
This is dtype AFTER conversion float64


array([1., 2., 3., 4., 5.])

In [63]:
#arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
#print("my name is float array and I am equal to",arr)
int_array = arr.astype(np.int32)
print("integer array is",int_array)

integer array is [1 2 3 4 5]


In [72]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)
print(numeric_strings.dtype)

conv_arr = numeric_strings.astype(float)
print(numeric_strings.dtype)
print(conv_arr.dtype)

|S4
|S4
float64


In [79]:
int_array = np.arange(10)
print("This is initial int array", int_array)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
conv_int_array = int_array.astype(float)
conv_int_array.dtype
int_array

This is initial int array [0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [82]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print("This is the array arr", arr)
print("Dimension of arr is:", arr.ndim)
arr * arr
#arr - arr

This is the array arr [[1. 2. 3.]
 [4. 5. 6.]]
Dimension of arr is: 2


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [83]:
1 / arr
#arr ** 2

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

Home work
Complete the indicated cells below by executing them

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
#print("This is array 2", arr2)
#print("This is array 1", arr)
arr2 - arr

In [ ]:
arr = np.arange(10)
arr
#print(arr[5])
arr[5:8]
arr[5:8] = 12
arr[5:8]
print(arr)

In [ ]:
arr_slice = arr[0:2]
arr_slice

In [ ]:
arr_slice[1] = 12345
arr

In [ ]:
arr_slice[:] = 64
arr

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

In [ ]:
arr2d[0][2]
#arr2d[0, 2]

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

In [ ]:
arr3d[0]

In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

In [ ]:
arr3d[1, 0]

In [ ]:
x = arr3d[1]
x
x[0]

In [ ]:
arr
arr[1:6]

In [ ]:
arr2d
arr2d[:2]

In [ ]:
arr2d[:2, 1:]

In [ ]:
lower_dim_slice = arr2d[1, :2]

In [ ]:
lower_dim_slice.shape

In [ ]:
arr2d[:2, 2]

In [ ]:
arr2d[:, :1]

In [ ]:
arr2d[:2, 1:] = 0
arr2d

In [ ]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
names
data

In [ ]:
names == "Bob"

In [ ]:
data[names == "Bob"]

In [ ]:
data[names == "Bob", 1:]
data[names == "Bob", 1]

In [ ]:
names != "Bob"
~(names == "Bob")
data[~(names == "Bob")]

In [ ]:
cond = names == "Bob"
data[~cond]

In [ ]:
mask = (names == "Bob") | (names == "Will")
mask
data[mask]

In [ ]:
data[data < 0] = 0
data

In [ ]:
data[names != "Joe"] = 7
data

In [ ]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
arr[[-3, -5, -7]]

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

Complete till here

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

In [ ]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr
np.dot(arr.T, arr)

In [ ]:
arr.T @ arr

In [ ]:
arr
arr.swapaxes(0, 1)

In [ ]:
samples = np.random.standard_normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1_000_000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.standard_normal(N)

In [ ]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))

In [ ]:
type(rng)

In [ ]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

In [ ]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)
x
y
np.maximum(x, y)

In [ ]:
arr = rng.standard_normal(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

In [ ]:
arr
out = np.zeros_like(arr)
np.add(arr, 1)
np.add(arr, 1, out=out)
out

In [ ]:
points = np.arange(-5, 5, 0.01) # 100 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

In [ ]:
#z = (xs ** 2 + ys ** 2)
#z

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

In [ ]:
plt.close("all")

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = rng.standard_normal((4, 4))
arr
arr > 0
np.where(arr > 0, 2, -2)

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
arr = rng.standard_normal((5, 4))
arr
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(axis=0)

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

In [ ]:
arr.cumsum(axis=0)
arr.cumsum(axis=1)

In [ ]:
arr = rng.standard_normal(100)
(arr > 0).sum() # Number of positive values
(arr <= 0).sum() # Number of non-positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

In [ ]:
arr = rng.standard_normal(6)
arr
arr.sort()
arr

In [ ]:
arr = rng.standard_normal((5, 3))
arr

In [ ]:
arr.sort(axis=0)
arr
arr.sort(axis=1)
arr

In [ ]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
sorted_arr2 = np.sort(arr2)
sorted_arr2

In [ ]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

In [ ]:
arr = np.arange(10)
np.save("some_array", arr)

In [ ]:
np.load("some_array.npy")

In [ ]:
np.savez("array_archive.npz", a=arr, b=arr)

In [ ]:
arch = np.load("array_archive.npz")
arch["b"]

In [ ]:
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)

In [ ]:
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

In [ ]:
np.dot(x, y)

In [ ]:
x @ np.ones(3)

In [ ]:
from numpy.linalg import inv, qr
X = rng.standard_normal((5, 5))
mat = X.T @ X
inv(mat)
mat @ inv(mat)

In [ ]:
import random
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)


In [ ]:
plt.figure()

In [ ]:
plt.plot(walk[:100])

In [ ]:
nsteps = 1000
rng = np.random.default_rng(seed=12345)  # fresh random generator
draws = rng.integers(0, 2, size=nsteps)
steps = np.where(draws == 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

In [ ]:
nwalks = 5000
nsteps = 1000
draws = rng.integers(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(axis=1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis=1)
crossing_times

In [ ]:
crossing_times.mean()

In [ ]:
draws = 0.25 * rng.standard_normal((nwalks, nsteps))